services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=quicknote'
      - 'MYSQL_PASSWORD=quicknote'
      - 'MYSQL_ROOT_PASSWORD=quicknote'
      - 'MYSQL_USER=quicknote'
    ports:
      - '3306:3306'
